### PR TITLE
Fix for issue #280

### PR DESCRIPTION
**Pull request by donschaefer**
Updates to resolve Issue #280

### CODE REVIEW

**Comment by donschaefer** [comment]
Temporarily blocked by an inability to run/debug the project locally. Will resume work when I have some more time & can troubleshoot the local issues that are preventing me from moving forward.

**Comment by LarsKemmann** [comment]
Thank you @donschaefer!! If you're having trouble, check out the updated readme file at the root of the project.

**Comment by LarsKemmann** [comment]
@donschaefer How close do you think this draft code is to being correct? Is it far enough along that I can take it from here?

**Comment by donschaefer** [comment]
I do not recall tbh - I'd say if you need to move this forward sooner rather than later, you'd probably be best served by starting fresh. All I recall offhand is that I was playing around with a few things that I thought would provide at least a starting point for a fix, but then ran into issues when I tried to run/test locally & never ended up circling back. 

Honestly, I don't think things had even gotten far enough to be considered a "checkpoint" (the point at which I'd normally commit and/or do a draft PR) & probably wouldn't have posted the draft PR at all had it not been for the project instructions encouraging draft PRs when any work has been started.

**Comment by donschaefer** [comment]
Hey @LarsKemmann - I _think_ I've added code that should achieve the desired behavior for all dialogs at this point, but given that I've only manually tested a handful of them, haven't taken the time to do a second pass for potential optimizations/refinements & haven't yet added any unit tests, I don't think this is ready to exit "Draft" status yet.

With that said though, if you don't feel like waiting for those updates, it should at least now be at a point where you can take it across the finish line.

**Comment by donschaefer** [comment]
@LarsKemmann - apologies for the lack of follow up on this. That said, given how busy things have gotten on my end, I wanted to give you a heads up that I'm unlikely to be able to add unit tests for this work any time soon. With that in mind, I'm going to remove "Draft" status & just suggest that you test it thoroughly and find an alternative route for getting unit tests added for this.

**Review by LarsKemmann — COMMENTED** [review]
The code updates look good! Sorry about the merge conflicts. 😌 I'll try to minimize those going forward. After you fix the latest (and last for now, I promise!) merge conflict, I'll run a test locally and then it should be good to merge!

**Comment by donschaefer** [comment]
Merge conflicts resolved :)

**Review by LarsKemmann — APPROVED** [review]
Nice work on this Don!! It's going to be a big help. I confirmed that it's working on most of the dialogs in the Family screen. I tested the 'Create Volunteer Family' dialog and that one didn't work for some reason (clicking on the backdrop closed it). Would you be able to take a systematic look at all the dialogs in the app when you have a chance and test each one, then submit any needed fixes in a follow-up PR?

**Comment by donschaefer** [comment]
@LarsKemmann - Apologies - I thought I had done a systematic review of the dialogs, but I'm guessing there are some syntax variations that I didn't happen to catch with my initial scans. That said, while I'm happy to take a 2nd pass at this, given your preference for transitioning to the use of fly-out components anyway, would it be more efficient to simply prioritize the dialogs that are still closing with backdrop clicks for that transition as we're able to?

**Comment by donschaefer** [comment]
@LarsKemmann - While the prior suggestion may still be a good one if issues persist, I think I found where things went wrong for several of the dialogs & it basically amounts to a bit of dyslexia on my part in the prior PR... I'll post a new PR shortly to fix those instances (which includes the one you found on 'Create Volunteer Family')!

**Pull request merged**
